restart-times: 3
cluster: "sbatch --parsable -p shared -t {resources.time} -n {resources.cpus} -N 1 --mem={resources.mem_mb} -o logs/slurm/{rule}_{wildcards}.out -e logs/slurm/{rule}_{wildcards}.err --account=grad_lab"
default-resources: [cpus=1, mem_mb=1000, time=60]
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
use-conda: true
conda-prefix:
jobs: 100
rerun-incomplete: true
cluster-status: "slurm-status.py"
